import "./normalize.css"
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import NavBar from './(sharedComponents)/NavBar/NavBar'
import Footer from './(sharedComponents)/Footer/Footer'
const mont = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <NavBar></NavBar>
          <div className="app-container">
          {children}
          </div>
        <Footer></Footer>
      </body>
    </html>
  )
}
